/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Tasks example
 * The tasks API description
 * OpenAPI spec version: 1.0
 */

export interface TaskResponseDto {
  createdAt: string;
  status: string;
  title: string;
  updatedAt: string;
}
